services:
  - type: web
    name: menuplan-simulator
    env: python
    region: frankfurt
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -c gunicorn.conf.py backend.app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0

